
spring:
  config:
    import: optional:file:.env[.properties]
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  r2dbc:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: r2dbcs:mysql://${DB_URL}/${DB_NAME}?useUnicode=true&characterEncoding=utf8&useSSL=false&sslMode=DISABLED&AllowPublicKeyRetrieval=True
server:
  port: 8888